app/__init__.py
from flask import Flask 
from .routes import main

def create_app():
    app = Flask(__name__)

    app.register_blueprint(main)

    return app

app/routes.py
from flask import Blueprint, render_template, request
from .services.weather.weather_service import WeatherService
from .services.weather.Robust_Entry import RobustEntry
from .services.helpers.form_helpers import get_form_data, validate_form_data, get_ticket_form_data, get_origin_destination
from .services.helpers.ticket_helpers import generate_ticket, save_ticket_to_csv, search_ticket_in_csv, process_ticket_entries
from .services.helpers.template_helpers import render_template_with_error
from .services.helpers.weather_helpers import get_weather_data_for_user
from .services.helpers.weather_helpers import get_recommendations

main = Blueprint('main', __name__)

def load_passwords():
    """
    Lee las contraseñas desde el archivo passwords.txt y las devuelve en un diccionario.
    La primera línea es la contraseña de sobrecargo y la segunda la de piloto.
    """
    try:
        with open('passwords.txt', 'r') as file:
            lines = file.readlines()
            sobrecargo_password = lines[0].strip()
            piloto_password = lines[1].strip()
            return {
                'sobrecargo': sobrecargo_password,
                'piloto': piloto_password
            }
    except FileNotFoundError:
        print("Error: No se encontró el archivo passwords.txt")
        return None
    except IndexError:
        print("Error: El archivo passwords.txt no tiene el formato esperado.")
        return None

@main.route('/', methods=['GET', 'POST'])
def index():
    error_message = None

    USER_PASSWORDS = load_passwords()
    if not USER_PASSWORDS:
        return render_template_with_error('index.html', "Error al cargar las contraseñas. Contacte al administrador.")

    if request.method == 'POST':
        city, user_type, password = get_form_data()

        error_message = validate_form_data(city, user_type, password, USER_PASSWORDS)
        if error_message:
            return render_template_with_error('index.html', error_message)

        weather_data, error_message = get_weather_data_for_user(city, user_type)
        if error_message:
            return render_template_with_error('index.html', error_message)
        
        recomendaciones = get_recommendations(weather_data['temperature'])

        return render_template('result.html', data=weather_data, user_type=user_type, recommendations=recomendaciones)

    return render_template('index.html', error=error_message)


@main.route('/ticket', methods=['GET', 'POST'])
def ticket():
    if request.method == 'POST':
        origin, destination = get_origin_destination()

        origin_entry, destination_entry, suggestion_message, error_message = process_ticket_entries(origin, destination)

        if error_message:
            return render_template_with_error('ticket.html', error_message)
        if suggestion_message:
            return render_template('ticket.html', suggestion=suggestion_message)

        ticket = generate_ticket(origin_entry['city'], destination_entry['city'])
        save_ticket_to_csv(origin_entry['city'], destination_entry['city'], ticket)

        return render_template('ticket_result.html', ticket=ticket)

    return render_template('ticket.html')

@main.route('/consultar_por_ticket', methods=['GET', 'POST'])
def consultar_por_ticket():
    USER_PASSWORDS = load_passwords()
    if not USER_PASSWORDS:
        return render_template_with_error('ticket_search.html', "Error al cargar las contraseñas. Contacte al administrador.")

    if request.method == 'POST':
        ticket, user_type, password = get_ticket_form_data()
        
        error_message = validate_form_data(ticket, user_type, password, USER_PASSWORDS)
        if error_message:
            return render_template_with_error('ticket_search.html', error_message)

        origin, destination = search_ticket_in_csv(ticket)
        if not destination:
            return render_template_with_error('ticket_search.html', f"No se encontró el ticket: {ticket}.")

        weather_data, error_message = get_weather_data_for_user(destination, user_type)
        if error_message:
            return render_template_with_error('ticket_search.html', error_message)
        
        recomendaciones = get_recommendations(weather_data['temperature'])

        return render_template('result.html', data=weather_data, user_type=user_type, origin=origin, destination=destination,recommendations=recomendaciones)

    return render_template('ticket_search.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Aboreto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Aboreto&family=Amaranth:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link rel="icon" href="static/css/images//LogoAW.jpeg" >
    <title>Clima En Tiempo Real</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">

</head>

<!--
{% if request.endpoint == 'main.index' %} home-page{% else %}other-page {% endif %}
-->
<body >
    <header>
        <b><a href="{{ url_for('main.index') }}" class="page-name-link" aria-label="Volver al menú principal">
            <div class="page-name">Clima En Tiempo Real</div>
        </a>
        </b>
        <a href="{{ url_for('main.index') }}">
            <img src="static/css/images/LogoAW.jpeg" alt="Logo" class="logo">
        </a>
    </header>
    
    <div id="loader" style="display: none;">
        <div class="spinner"></div>
    </div>

    <div class="hero-section">

        <div class="t-background">

                {% block content %}{% endblock %}

        </div>
     

    </div>
   
    <script>
        const form = document.querySelector('form');
        const loader = document.getElementById('loader');
        const links = document.querySelectorAll('a');  // Selecciona todos los enlaces (para navegación con el loader)
        
        if (form) {
            form.addEventListener('submit', function() {
                loader.style.display = 'block';  // Show the loader when form is submitted
            });
        }

        links.forEach(link => {
            link.addEventListener('click', function() {
                loader.style.display = 'block';  // Muestra el loader al hacer clic en un enlace
            });
        });
    </script>
   

</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="overlay-text">        
    <h1>Consulta el clima por ciudad</h1>
</div>
<main>

    <form method="POST" autocomplete="off">
        <h2>Ingrese los datos</h2>
        {% if error %}
        <div class="alert alert-danger mt-3" role="alert">
            {{ error }}
        </div>
        {% endif %}
        
        {% if suggestion %}
        <div class="alert alert-warning mt-3" role="alert">
            {{ suggestion }}
        </div>
        {% endif %}

        <label for="city">Ciudad:</label>
        <input type="text" id="city" name="city" required>
        
        <label for="user_type">Seleccionar tipo usuario:</label>
        <select id="user_type" name="user_type" required onchange="togglePasswordField()">
            <option value="turista">Turista</option>
            <option value="sobrecargo">Sobrecargo</option>
            <option value="piloto">Piloto</option>
        </select>

        <!-- Campo de contraseña que solo se muestra si se selecciona sobrecargo o piloto -->
        <div id="password-field" style="display: none;">
            <label for="password">Contraseña:</label>
            <div class="input-group mb-3">
                <input type="password" class="form-control" id="password" name="password" placeholder="Ingrese su contraseña">
                <span class="input-group-text" id="togglePassword" style="cursor: pointer;" onclick="togglePasswordVisibility()">
                    <i class="far fa-eye"></i>
                </span>
            </div>
        </div>

        <button type="submit">Consultar clima</button>
    </form>

 

    <div class="ticket-section">

    <h2 class="ticket-title">¿Quieres consultar el clima con un ticket?</h2>
    <a href="{{ url_for('main.consultar_por_ticket') }}">
    <button class="generate-ticket-button">Consultar con Ticket</button>
    </a>

       

        <h2 class="ticket-title">¿No conoces el ticket de tu vuelo?</h2>
        <a href="{{ url_for('main.ticket') }}">
            <button class="generate-ticket-button">Generar Ticket</button>
        </a> 
    </div>
</main>
<!-- JavaScript para mostrar/ocultar el campo de contraseña -->
<script>
function togglePasswordField() {
    var userType = document.getElementById('user_type').value;
    var passwordField = document.getElementById('password-field');
    
    // Mostrar el campo de contraseña solo si el usuario selecciona sobrecargo o piloto
    if (userType === 'sobrecargo' || userType === 'piloto') {
        passwordField.style.display = 'block';
    } else {
        passwordField.style.display = 'none';
    }
}
</script>
<script>
    function togglePasswordVisibility() {
        var passwordField = document.getElementById("password");
        var toggleIcon = document.getElementById("togglePassword");
    
        // Alternar entre tipo "password" y "text"
        if (passwordField.type === "password") {
            passwordField.type = "text";
            toggleIcon.classList.remove("fa-eye");
            toggleIcon.classList.add("fa-eye-slash");  // Cambiar al icono de ojo tachado
        } else {
            passwordField.type = "password";
            toggleIcon.classList.remove("fa-eye-slash");
            toggleIcon.classList.add("fa-eye");  // Cambiar al icono de ojo normal
        }
    }
    </script>   

{% endblock %}

app/templates/result.html
{% extends 'base.html' %}

{% block content %}
<div class="overlay-text">        
    <h2>Resultados</h2>
</div>

<div class="weather-container">
        <h3>Clima de {{ data.city }}</h3>
        <div class="info-box">
            <div>
            {% if user_type == 'turista' %}
                <p>Temperatura: {{ data.temperature }}°C</p>
                <p>Descripción: {{ data.description }}</p>
            {% elif user_type == 'sobrecargo' %}
                <p>Temperatura: {{ data.temperature }}°C</p>
                <p>Humedad: {{ data.humidity }}%</p>
                <p>Visibilidad: {{ data.visibility }} metros</p>
            {% elif user_type == 'piloto' %}
                <p>Temperatura: {{ data.temperature }}°C</p>
                <p>Latitud: {{ data.lat }}</p>
                <p>Longitud: {{ data.lon }}</p>
                <p>Velocidad del viento: {{ data.wind_speed }} m/s</p>
                <p>Presión: {{ data.pressure }} hPa</p>
            {% else %}
                
            {% endif %}
            </div>

            <img src="{{data.icon}}"></p>
        </div>

</div>




<div class="recommendations">
    <h3>Recomendaciones</h3>
    <ul>
        {% for recommendation in recommendations %}
            <li>{{ recommendation }}</li>
        {% endfor %}
    </ul>
</div>




<div class="buttons">
    <a href="{{ url_for('main.index') }}">
        <button >Menú principal</button>
    </a>
    <a href="{{ url_for('main.consultar_por_ticket') }}">
        <button >Consultar otra ciudad por Ticket</button>
    </a>
</div>

{% endblock %}

app/templates/ticket.html
{% extends 'base.html' %}

{% block content %}
<div class="overlay-text">        
    <h1>Generar ticket</h1>
</div>
<main>


<form method="POST" autocomplete="off">
    <h2>Ingresa los datos</h2>

    {% if error %}
    <div class="alert alert-danger mt-3" role="alert">
        {{ error }}
    </div>
    {% endif %}
    
    {% if suggestion %}
    <div class="alert alert-warning mt-3" role="alert">
        {{ suggestion }}
    </div>
    {% endif %}

    <label for="origin">Ciudad de origen:</label>
    <input type="text" id="origin" name="origin" required>

    <label for="destination">Ciudad de destino:</label>
    <input type="text" id="destination" name="destination" required>

    <button type="submit">Generar Ticket</button>
   
    <div class="buttons">
        <a href="{{ url_for('main.index') }}">
            <button type="button">Menú principal</button>
        </a>
    </div>
</form>

{% if ticket %}
<p>Tu ticket generado es: <strong>{{ ticket }}</strong></p>
{% endif %}




</main>

{% endblock %}

app/templates/ticket_result.html
{% extends 'base.html' %}

{% block content %}
<div class="ticket-result">
    <h2 class="ticket-title">Ticket Generado</h2>

    {% if ticket %}
        <p class="ticket-code">Tu ticket es: <strong>{{ ticket }}</strong></p>
    {% else %}
        <p>Lo sentimos, no se pudo generar el ticket.</p>
    {% endif %}

    <div class="buttons">
        <a href="{{ url_for('main.index') }}">
            <button>Menu principal</button>
        </a>

        <a href="{{ url_for('main.consultar_por_ticket') }}">
            <button>Consular clima con ticket</button>
        </a>
    </div>
</div>
{% endblock %}

app/templates/ticket_search.html
{% extends 'base.html' %}

{% block content %}
<h2>Consultar por Ticket</h2>

<form method="POST" autocomplete="off">
    <label for="ticket">Ingrese su ticket:</label>
    <input type="text" id="ticket" name="ticket" required>

    <label for="user_type">Seleccionar tipo usuario:</label>
    <select id="user_type" name="user_type" required onchange="togglePasswordField()">
        <option value="turista">Turista</option>
        <option value="sobrecargo">Sobrecargo</option>
        <option value="piloto">Piloto</option>
    </select>

    <!-- Campo de contraseña que solo se muestra si se selecciona sobrecargo o piloto -->
    <div id="password-field" style="display: none;">
        <label for="password">Contraseña:</label>
        <div class="input-group mb-3">
            <input type="password" class="form-control" id="password" name="password" placeholder="Ingrese su contraseña">
            <span class="input-group-text" id="togglePassword" style="cursor: pointer;" onclick="togglePasswordVisibility()">
                <i class="far fa-eye"></i>
            </span>
        </div>
    </div>
    
    
    <button type="submit">Consultar</button>
</form>

{% if error %}
<div class="alert alert-danger mt-3" role="alert">
    {{ error }}
</div>
{% endif %}

<div class="buttons">
    <a href="{{ url_for('main.index') }}">
        <button>Regresar al menú principal</button>
    </a>
</div>

<!-- JavaScript para mostrar/ocultar el campo de contraseña -->
<script>
function togglePasswordField() {
    var userType = document.getElementById('user_type').value;
    var passwordField = document.getElementById('password-field');
    
    // Mostrar el campo de contraseña solo si el usuario selecciona sobrecargo o piloto
    if (userType === 'sobrecargo' || userType === 'piloto') {
        passwordField.style.display = 'block';
    } else {
        passwordField.style.display = 'none';
    }
}
</script>
<script>
    function togglePasswordVisibility() {
        var passwordField = document.getElementById("password");
        var toggleIcon = document.getElementById("togglePassword");
    
        if (passwordField.type === "password") {
            passwordField.type = "text";
            toggleIcon.classList.remove("fa-eye");
            toggleIcon.classList.add("fa-eye-slash");
        } else {
            passwordField.type = "password";
            toggleIcon.classList.remove("fa-eye-slash");
            toggleIcon.classList.add("fa-eye");
        }
    }
    </script>

{% endblock %}